// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0c0G37rn9D8CibBkQZSJgFkJ7WBzekg',
    appId: '1:58032615253:web:0d2d086fafad33fa2c89dc',
    messagingSenderId: '58032615253',
    projectId: 'greensteps-6d040',
    authDomain: 'greensteps-6d040.firebaseapp.com',
    storageBucket: 'greensteps-6d040.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrXKjDrvgFgwPwvQOapJMtbGVcMQi2V-U',
    appId: '1:58032615253:android:e193e52e6ddc52312c89dc',
    messagingSenderId: '58032615253',
    projectId: 'greensteps-6d040',
    storageBucket: 'greensteps-6d040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuibFvgZiHCnPFbmTtlK6XRsz45BRASY0',
    appId: '1:58032615253:ios:39185b5ea0db037d2c89dc',
    messagingSenderId: '58032615253',
    projectId: 'greensteps-6d040',
    storageBucket: 'greensteps-6d040.appspot.com',
    iosBundleId: 'com.example.greensteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuibFvgZiHCnPFbmTtlK6XRsz45BRASY0',
    appId: '1:58032615253:ios:39185b5ea0db037d2c89dc',
    messagingSenderId: '58032615253',
    projectId: 'greensteps-6d040',
    storageBucket: 'greensteps-6d040.appspot.com',
    iosBundleId: 'com.example.greensteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0c0G37rn9D8CibBkQZSJgFkJ7WBzekg',
    appId: '1:58032615253:web:cc0cc509f54fb2ad2c89dc',
    messagingSenderId: '58032615253',
    projectId: 'greensteps-6d040',
    authDomain: 'greensteps-6d040.firebaseapp.com',
    storageBucket: 'greensteps-6d040.appspot.com',
  );
}
